project_id: your-project-id  # Replace with your Google Cloud project ID
subscription_id: your-subscription-id # Replace with your Pub/Sub subscription ID
some_other_setting: some_value   # Any other settings you need
